baseURL = "http://blog.ehmiiz.tech/"
languageCode = "en-us"
title = "Ehmiiz.tech - A book blog"
theme = "paperesque"
copyright = "© 2021 Emil Larsson"

[[params.menu]]
  name = "Books reviews"
  url = "posts/"


[[params.menu]]
  name = "About"
  url = "about/"

[[params.menu]]
name = "GitHub"
url = "https://github.com/ehmiiz/"

[[params.topmenu]]
name = "Posts"
url = "posts/"


[[params.topmenu]]
name = "About"
url = "about/"

[[params.topmenu]]
name = "GitHub"
url = "https://github.com/ehmiiz/"

[[params.topmenu]]
name = "RSS"
url = "posts/index.xml"