baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ehmiiz.tech - A book blog"
theme = "paperesque"
copyright = "© 2021 Emil Larsson"

[[params.menu]]
  name = "Blog"
  url = "posts/"


[[params.menu]]
  name = "About"
  url = "about/"

[[params.topmenu]]
name = "about"
url = "about/"

[[params.topmenu]]
name = "rss"
url = "posts/index.xml"